version: 2.1
commands:
  add-ssh-key:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ee:c8:1d:d9:f8:89:83:6e:66:b7:a6:68:c0:f6:45:b4"
  install-dependencies:
    steps:
      - run:
          command: |
            make install_pipenv
            make init
  configure-git-user:
    steps:
      - run:
          command: |
            git config user.email "ooz@users.noreply.github.com"
            git config user.name "ooz"
jobs:
  test:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - install-dependencies
      - run:
          command: |
            make test
      - store_artifacts:
          path: htmlcov

  build-and-deploy:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - install-dependencies
      - add-ssh-key
      - configure-git-user
      - run:
          command: |
            make deploy

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - test
      - build-and-deploy:
          requires:
            - test
          filters:
            branches:
              only: master
